### PR TITLE
Update for rippled version 1.6.0

### PR DESCRIPTION
**Pull request by ximinez**
Updated the code to build with the updated rippled 1.6.0 dependency. Uses the `FetchContent` method used by https://github.com/ripple/validator-keys-tool to use installed rippled or dynamically pull the rippled branch based on the checked-out branch. Currently will only work with develop, but should start working automatically once the 1.6.0 beta code in develop is officially released.

This will have to wait until rippled 1.6.0 is released, and assumes it includes https://github.com/ripple/rippled/pull/3449 and ripple/rippled#3532

---
This change is [Reviewable](https://reviewable.io/reviews/ximinez/ripple-offline-tool/8)

### CODE REVIEW

**Comment by mellery451** [comment]
@scottschurr you might have a typo somewhere...the variable I expect to see is `CMAKE_BUILD_TYPE`. If that was just a typo in your message, than please ignore me.

**Comment by scottschurr** [comment]
Thanks @mellery451.  Yup.  It was a typo in my script.  I fixed the typo and the warning is gone.  Thanks for the help.  And I hope things are going well at your end.  Nice to hear from you.

**Comment by gregtatcam** [comment]
___
*[README.md, line 51 at r1](https://reviewable.io/reviews/ximinez/ripple-offline-tool/8#-MFbiZbz2hiA7I2_L0au:-MFbiZbz2hiA7I2_L0av:bdcb11x) ([raw file](https://github.com/ximinez/ripple-offline-tool/blob/abec1dd8dd349d9d321662d56e96d36182dc938a/README.md#L51)):*
> ```Markdown
> $ cd ${YOUR_RIPPLE_SERIALIZE_DIRECTORY}
> $ mkdir -p build/gcc.debug
> $ cd build/gcc.debug
> ```

Should be build/gcc.release?

**Comment by ximinez** [comment]
@gregtatcam Good catch. The way it's written, it should. Instead, I changed it to just use `build`, because nothing in the instructions specifies gcc either.

**Comment by ximinez** [comment]
@gregtatcam, @pwang200, @scottschurr Does anybody want to chime in about those last couple of corrections before I go ahead and merge this.

**Comment by gregtatcam** [comment]
> @gregtatcam, @pwang200, @scottschurr Does anybody want to chime in about those last couple of corrections before I go ahead and merge this.

LGTM :+1:

**Pull request merged**
